server:
  port: 10001
spring:
  application:
    name: service-consumer-feign
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 2
        sleepWindowInMilliseconds: 5000